### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by susumuota** [Blue-Pix/note-dark#2]
Users cannot add extension via link like this. 

https://chrome.google.com/webstore/detail/ndjhheglhimmpjbgedbacgmloigpicng/publish-accepted?authuser=1&hl=ja

I could add it via this link.

https://chrome.google.com/webstore/detail/ndjhheglhimmpjbgedbacgmloigpicng/

**Comment by Blue-Pix** [comment]
Thanks for your kindly report🎉
